# Generated by Django 3.1.5 on 2021-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0047_auto_20200810_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="tax_id",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
